### ISSUE TITLE
Routing (Direct vs Block)

### ISSUE THREAD

**Issue by xxamr** [iranxray/hope#44]
If possible please create a routing code to make the Iranian websites be accessed direct not to be blocked by the server.
in this code you have written, all Iran hosted websites will be blocked when you are connected trough VPN
Thanks

**Comment by Jabi-james** [comment]
Exactly what I was going to open an issue about..
To access Iranian websites, we have to turn the V2ray service on and off again and again if we follow [this method](https://github.com/iranxray/hope/blob/main/routing.md#%DA%AF%D8%A7%D9%85-%D9%BE%D9%86%D8%AC%D9%85-%D8%A7%D8%AE%D8%AA%DB%8C%D8%A7%D8%B1%DB%8C)..
So can we just write down " direct " in the routing section of Xray setting on the panel instead of " blocked " ?

![Screenshot 2023-02-04 151338](https://user-images.githubusercontent.com/91572300/216765980-8331942a-29c4-4a46-af41-8bcd88f0e190.jpg)

**Comment by xxamr** [comment]
Great. I will check it out right now

**Comment by xxamr** [comment]
Hi Again
Changing "blocked" to "Direct" does not work.
After changing that, all the traffic go through the xRay server. you can check it out by visiting: es.tamin.ir

It says: you are abroad and the access is restricted

**Comment by Jabi-james** [comment]
> Hi Again Changing "blocked" to "Direct" does not work. After changing that, all the traffic go through the xRay server. you can check it out by visiting: es.tamin.ir
> 
> It says: you are abroad and the access is restricted

Yeah,  "direct" does not work on server, it just blocks "ir"" IP and domains,,

**Comment by iranxray** [comment]
سلام رفقا. روش direct از روی سرور کار نمی‌کنه. در سرور فقط می‌تونید block‌ کنید. مفهوم direct یه مفهوم سمت کاربره. در همین مستند routing‌ قسمتی هم گذاشتیم که میگه چطوری IP های ایران رو direct کنیم. اون رو امتحان کردید؟

**Comment by xxamr** [comment]
نه امتحان نکردیم. ممنون میشم بیشتر راهنمایی کنید
